spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/e4c
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: false
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${hostGoogle}
    port: 587
    username: ${emailGoogle}
    password: ${passwordGoogle}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
